server:
  port: 7006 # 设置端口

site:
  url: http://live.example.org # 指明项目部署的可访问的 url（应当被 nginx 等指向 gateway 的本地 url）
  gatewayUrl: http://localhost:7007 # 指明 gateway 部署的本地 url
  files: D:/site # 指明项目用于保存用户上传资源的地址
  nicksBanned: miku,Miku,MIKU,Operacon,operacon # 保留的不能注册 nickname，必须不为空

nms:
  http: http://localhost:8888 # 指明 nms 部署的 http 地址
  rtmp: rtmp://localhost  # 指明 nms 部署的 rtmp 地址
  secret: exampleKey  # 指明 nms 推流鉴权的 secret
  api_user: admin # 指明 nms API 用户名
  api_pass: admin # 指明 nms API 密码
  speed_up: 20 # 指明 nms 所在服务器的上传带宽，用于计算负载。单位 Mbit/s
  speed_down: 50 # 指明 nms 所在服务器的下载带宽，用于计算负载。单位 Mbit/s

spring:
  application:
    name: imikuLive
  datasource:
    url: # 数据源
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifeTime: 600000
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  mail:
    protocol: smtp
    host: # 必须设置 smtp 用于用户注册和密码找回
    port: 25
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: false
            required: false
  servlet:
    multipart: # 上传文件的最大大小，涉及头像和房间封面
      max-file-size: 10MB
      max-request-size: 10MB

socketio:
  host: localhost
  port: 7005
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口 boss 线程组为 1 即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认 10 秒。HTTP握手升级为 ws 协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认 60 秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认 25 秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000